### PR TITLE
Deprioritize keys

### LINKED ISSUE #21: Strings that are part of a sequence are highlighted incorrectly if they contain a colon
Strings that are part of a sequence are highlighted incorrectly if they contain a colon:

```yaml
assignment: 'Sections 2.4 and 4.1'
problems: 
- 'Section 2.4: 3, 6abc, 12ab, 30, 32a'
- 'Section 4.1: 10ac, 12ab, 13ac, 14ac, 28, 30, 38, 40'
- 'Section 2.4 - 3, 6abc, 12ab, 30, 32a'
- 'Section 4.1 - 10ac, 12ab, 13ac, 14ac, 28, 30, 38, 40'
```

### PR DESCRIPTION
**Pull request by 50Wliu**
Fixes #21

/cc @rpendleton @szhu @Yajo @code-tree @Ajedi32: if one of you could test this out, that would be appreciated.  Let me know if you need instructions on how to link this with Atom.

### CODE REVIEW

**Comment by Yajo** [comment]
Instructions, please

**Comment by Ajedi32** [comment]
Seems to be working:

image

**Comment by Ajedi32** [comment]
@Yajo:

    apm develop language-yaml language-yaml # Clone the project to the current directory
    cd language-yaml/ # cd to the newly cloned project directory
    git checkout wl-prioritize-strings # Checkout this PR

Then:

1. Open Atom
2. Press `Ctrl+Shift+P` to open the command pallet
3. Select `Application: Open Dev`
4. Open a folder
5. Test your changes

Not sure if that works by on Windows though, since it apparently symlinks `~/atom/dev/packages/language-yaml` to the cloned directory, and Windows doesn't allow non-root users to create symlinks. @50Wliu, would you happen to know how that works?

**Comment by 50Wliu** [comment]
It does work!  `apm` uses the `junction` symlink which doesn't require Administrator escalation.

**Pull request merged**
